# Generated by Django 5.0.1 on 2024-01-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitie',
            name='university_name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
